#!/usr/bin/tcsh

# $1 sim

set blist = `ls /home/students/cs/benchmarks/champsim/ | grep gz | sed "s/.trace.gz//g"`

set plist = '22020202 22420202 23020202 23420202'
#set plist = '22020202'

echo 'executable = /home/faculty/yanos/RES/REPL-new/SADRRIP/run_1champ.sh'
echo 'universe = vanilla'
echo 'getenv = True'
echo 'notification = error'
echo 'requirements = ( ((Arch == "INTEL") || (Arch == "X86_64" )) )'
echo 'Initialdir = /home/faculty/yanos/RES/REPL-new/SADRRIP/'

#foreach bench ($blist)
foreach bench (Roms)

#run_1champ.sh $1 100 500 $bench "$plist" &

echo 'arguments ='$1 1 1 $bench '\"'$plist'\"'
echo 'output =/home/faculty/yanos/RES/REPL-new/SADDRIP/condor-out-err/'$bench.$1.out
echo 'error =/home/faculty/yanos/RES/REPL-new/SADDRIP/condor-out-err/'$bench.$1.err
echo 'log =/home/faculty/yanos/RES/REPL-new/SADDRIP/condor-out-err/'$bench.$1.log

echo Queue

end


