#!/usr/bin/tcsh

set v1 = `SAcommon | gawk '{if (NR==1) print $0}'`
set v2 = `SAcommon | gawk '{if (NR==2) print $0}'`

setenv RESULTS $v1
setenv SCRIPTS $v2
#
# $1 sim
# $2 replacement policy

#set RESULTS = /home/faculty/yanos/RES/REPL-new/RESULTS
#set RESULTS = /home/faculty/yanos/RES/REPL-new/SADRRIP/results


set blist = `ls /home/students/cs/benchmarks/champsim/ | grep gz | sed "s/.trace.gz//g"`

setenv RES $RESULTS/results-$1-$2

foreach bench ($blist)

echo -n $bench" "
grep Heartbeat $RES/$bench.out | tail -1 

end
