#!/usr/bin/tcsh

set v1 = `SAcommon | gawk '{if (NR==1) print $0}'`
set v2 = `SAcommon | gawk '{if (NR==2) print $0}'`

setenv RESULTS $v1
setenv SCRIPTS $v2
#
#set RESULTS = /home/faculty/yanos/RES/REPL-new/RESULTS
#set RESULTS = /home/faculty/yanos/RES/REPL-new/SADRRIP/results



#foreach  p1 (results*-prefetch-*)
foreach  p1 ($RESULTS/results-srrip-flex*-prefetch-*-*42420202*15)



#foreach p2 (results*-prefetch-*)
foreach  p2 ($RESULTS/results-srrip-flex*-prefetch-*-*03430202*132)



#foreach p3 (results*-prefetch-*)
foreach  p3 ($RESULTS/results-srrip-flex*-prefetch-*)

foreach p4 ($RESULTS/results-srrip-flex*-prefetch-*)


echo -n $p1 $p2 $p3 $p4 " "

grep Finished $p1/* $p2/* $p3/* $p4/* | gawk 'BEGIN{l[1]=0.652472;l[2]=1.01608;l[3]=0.75258;l[4]=0.723997;l[5]=1.12738;l[6]=0.619121;l[7]=0.354975;l[8]=2.14553;l[9]=0.642067;l[10]=0.547979;l[11]=0.393314;l[12]=0.24396;l[13]=0.923689;l[14]=0.44615;l[15]=0.355321;l[16]=1.07814;l[17]=0.820884;l[18]=1.36365;l[19]=0.392917;l[20]=0.891657}{r[NR]=$10}END{if (NR==80){a=0;for(i=1;i<=NR/4;++i){t=(r[i]>r[i+NR/4]?r[i]:r[i+NR/4]); t=(t>r[i+2*NR/4]?t:r[i+2*NR/4]); a+=((t>r[i+3*NR/4]?t:r[i+3*NR/4])/l[i])};print a/(NR/4)}else print -1}'


end

end



end



end
