#!/usr/bin/tcsh

set v1 = `SAcommon | gawk '{if (NR==1) print $0}'`
set v2 = `SAcommon | gawk '{if (NR==2) print $0}'`

setenv RESULTS $v1
setenv SCRIPTS $v2
#
#set SCRIPTS = /home/faculty/yanos/RES/REPL-new/SCRIPTS
#set SCRIPTS = /home/faculty/yanos/RES/REPL-new/SADRRIP

$SCRIPTS/proc-stats $1 $3 $4 $5 0 > t11

$SCRIPTS/proc-stats $2 $3 $4 $5 0 > t12

paste t11 t12 | gawk -vf=$6 '{p=NF/2-f+1;for(i=NF-f+1;i<=NF;i++) {printf "%6.2f ", $p-$i;++p};printf "\n";}' > t21

$SCRIPTS/proc-stats $1 $3 $4 $5 1 > t13

$SCRIPTS/proc-stats $2 $3 $4 $5 1 > t14

paste t13 t14 | gawk  '{printf "%6.2f\n", $1-$2}' > t43

$SCRIPTS/proc-stats $1 $3 $4 $5 2 > t15

$SCRIPTS/proc-stats $2 $3 $4 $5 2 > t16

cat t15 t16 > t54 

paste t54 t21 t43 t11 t13 t12 t14 

rm t13 t14 t21 t43 t54 t15 t16 t11 t12

