#!/bin/tcsh

#SBATCH -A local
#SBATCH -p COMPUTE

set home_path = "/home/pchatz06/RRIP_work/pchatz06_work/SADRRIP"
set binary_path = "/home/pchatz06/RRIP_work/pchatz06_work/SADRRIP/bin"

set executable = "run_1champ.sh"
set binary = "perceptron-next_line-ip_stride-drrip-flex-1core"

set pselist = '10'
set pselmask = '1'
set dsalgo = '0'
set window = '0'
set srthr = '0'
set brthr = '0'
set boost = '0'
set hitmask = '0'

set bcode = $1
set plist = $2
set dirty_plist = $3
set demmask = $4
set id = $5

set warmup_inst = 100
set sim_inst = 500

switch($bcode)

case 1:
$home_path/$executable $binary $warmup_inst $sim_inst "Blender" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 2:
$home_path/$executable $binary $warmup_inst $sim_inst "Bwaves" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 3:
$home_path/$executable $binary $warmup_inst $sim_inst "cactuBSSN" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 4:
$home_path/$executable $binary $warmup_inst $sim_inst "Cam4" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 5:
$home_path/$executable $binary $warmup_inst $sim_inst "Exchange" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 6:
$home_path/$executable $binary $warmup_inst $sim_inst "Fotonik3d" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 7:
$home_path/$executable $binary $warmup_inst $sim_inst "Gcc" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 8:
$home_path/$executable $binary $warmup_inst $sim_inst "Imagick" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 9:
$home_path/$executable $binary $warmup_inst $sim_inst "Lbm" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 10:
$home_path/$executable $binary $warmup_inst $sim_inst "Leela" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 11:
$home_path/$executable $binary $warmup_inst $sim_inst "Mcf" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 12:
$home_path/$executable $binary $warmup_inst $sim_inst "Omnetpp" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 13:
$home_path/$executable $binary $warmup_inst $sim_inst "Parest" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 14:
$home_path/$executable $binary $warmup_inst $sim_inst "Perlbench" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 15:
$home_path/$executable $binary $warmup_inst $sim_inst "Povray" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 16:
$home_path/$executable $binary $warmup_inst $sim_inst "Roms" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 17:
$home_path/$executable $binary $warmup_inst $sim_inst "Wrf" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 18:
$home_path/$executable $binary $warmup_inst $sim_inst "x264" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 19:
$home_path/$executable $binary $warmup_inst $sim_inst "Xalancbmk" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

case 20:
$home_path/$executable $binary $warmup_inst $sim_inst "Xz" "$plist" "$pselist" "$pselmask" "$dsalgo" "$window" "$srthr" "$brthr" "$boost" "$hitmask" "$demmask" "$dirty_plist" "$id"
breaksw

endsw

