#!/bin/tcsh

set dir = results/results-drrip-flex-slope-prefetch-debug-1core-0747070742030202-10-3-1-64-35-35


foreach bench ($dir/*) 

#echo $bench

echo 'set y2tics; plot "< gawk' "'"'{if ($1==\"DSA:\") print $0}'"'" $bench'"' "using 4 axes x1y2, ''using 9, '' using (16*"'$'"3) with l axes x1y2, -22 with l axes x1y2,22 with l axes x1y2" | gnuplot -p -

#plot "< gawk '{if ($1==\"PSEL:\") print $2}' $bench using 1 with do, "< gawk -vw=64 '{if ($1==\"PSEL:\"){sl=$2-q[(NR-1)%w];q[(NR-1)%w]=$2; print sl/64}}' $bench " using 1 with l axes x1y2

end
