#!/usr/bin/tcsh

# $1 bench start-id
# $2 bench num
# $3 name ext
# $4 type of output to produce (1 is synopsis 2 more detailed)

set blist = `ls /home/students/cs/benchmarks/champsim/ | grep gz | sed "s/.trace.gz//g" |gawk -vb=$1 -vn=$2 '{if (NR>=b && NR<b+n) printf "%s ",$i}'`


set v1 = `SAcommon | gawk '{if (NR==1) print $0}'`
set v2 = `SAcommon | gawk '{if (NR==2) print $0}'`

setenv RESULTS $v1
setenv SCRIPTS $v2
#

# directory with result folders -- differetn user need to change this to his/her folder
#set RESULTS = /home/faculty/yanos/RES/REPL-new/RESULTS
#set RESULTS = /home/faculty/yanos/RES/REPL-new/SADRRIP/results

# directory with script folders -- differetn user need to change this to his/her folder
#set SCRIPTS = /home/faculty/yanos/RES/REPL-new/SCRIPTS
#set SCRIPTS = /home/faculty/yanos/RES/REPL-new/SADRRIP

touch tk kt tkt
rm  tk kt tkt
touch tk

foreach bench ($blist)

#echo -n $bench " "

#i assume all result folder start with results...

foreach  pol ($RESULTS/results*-$3*)


#gawk 'BEGIN{pn=2;nt=4;mt=2;ut=2;st=4;vt=16;for(a=0;a<pn;a++)for(b=0;b<nt;++b)for(c=0;c<mt;++c)for(d=0;d<ut;++d)for(e=0;e<st;++e)for(f=0;f<vt;++f) {m[a,b,c,d,e,f]=0;h[a,b,c,d,e,f]=0;}}{if ($1=="STAN-MISSES"){m[$3,$4,$5,$6,$7,$8]+=$9}else if ($1=="STAN-HITS"){h[$3,$4,$5,$6,$7,$8]+=$9}}END{for(a=0;a<pn;a++)for(b=0;b<nt;++b)for(c=0;c<mt;++c)for(d=0;d<ut;++d)for(e=0;e<st;++e)for(f=0;f<vt;++f) if (m[a,b,c,d,e,f]!=0) print a,b,c,d,e,f,m[a,b,c,d,e,f]}' $pol/$bench.out  

#gawk 'BEGIN{pn=2;nt=4;mt=2;ut=2;st=4;vt=16;for(a=0;a<pn;a++){ma[a]=0;ha[a]=0;for(b=0;b<nt;++b){mb[b]=0;hb[b]=0;for(c=0;c<mt;++c){mc[c]=0;hc[c]=0;for(d=0;d<ut;++d){md[d]=0;hd[d]=0;for(e=0;e<st;++e){me[e]=0;he[e]=0;for(f=0;f<vt;++f){mf[f]=0;hf[f]=0;m[a,b,c,d,e,f]=0;h[a,b,c,d,e,f]=0;}}}}}}}{if ($1=="STAN-MISSES"){ma[$3]+=$9;mb[$4]+=$9;mc[$5]+=$9;md[$6]+=$9;me[$7]+=$9;mf[$8]+=$9;m[$3,$4,$5,$6,$7,$8]+=$9}else if ($1=="STAN-HITS"){ha[$3]+=$9;hb[$4]+=$9;hc[$5]+=$9;hd[$6]+=$9;he[$7]+=$9;hf[$8]+=$9;h[$3,$4,$5,$6,$7,$8]+=$9}}END{for(a=0;a<pn;a++)print ma[a],ha[a];for(b=0;b<nt;++b)print mb[b],hb[b];for(c=0;c<mt;++c)print mc[c],hc[c];for(d=0;d<ut;++d)print md[d],hd[d];for(e=0;e<st;++e)print me[e],he[e];for(f=0;f<vt;++f) print mf[f],hf[f];}' $pol/$bench.out  

gawk -vout=$4 -f $SCRIPTS/ing  $pol/$bench.out  > tkt

paste tk tkt > kt

mv kt tk

end

end

cat tk
rm tk tkt
