./run.sh local Blender
./run.sh local Bwaves
./run.sh local Cam4
./run.sh local cactuBSSN
./run.sh local Exchange
./run.sh local Gcc
./run.sh local Lbm
./run.sh local Mcf
./run.sh local Parest
./run.sh local Povray
./run.sh local Wrf
./run.sh local Xalancbmk
./run.sh local Fotonik3d
./run.sh local Imagick
./run.sh local Leela
./run.sh local Omnetpp
./run.sh local Perlbench
./run.sh local Roms
./run.sh local x264
./run.sh local Xz
./run.sh global Blender:Bwaves:Cam4:cactuBSSN:Exchange:Gcc:Lbm:Mcf:Parest:Povray:Wrf:Xalancbmk:Fotonik3d:Imagick:Leela:Omnetpp:Perlbench:Roms:x264:Xz