#!/usr/bin/tcsh

@ i= 1;

# 6 8 9 11 12

#foreach hos (25 26 27 28 29)
#foreach hos (20 21 22 23 24)
foreach hos (13 14 16 18 19)
#foreach hos (15 17 31 32 33)
#foreach hos (25 26 27 28 29 20 21 22 23 24 13 14 16 18 19 15 17 31 32 33)

#### ssh yanos@b103ws$hos 'cd RES/REPL-new/SADRRIP; hostname; ./run-bench sa-drrip-flex-prefetch-1core '$i ' 4 >&' err.$hos

#### 
ssh yanos@b103ws$hos 'cd RES/REPL-new/SADRRIP; hostname; ./run-bench drrip-flex-dem-prefetch-1core '$i ' 4 >&' err.$hos

#### ssh yanos@b103ws$hos 'cd RES/REPL-new/SADRRIP; hostname; ./run-bench srrip-flex-dem-prefetch-1core '$i ' 4 >&' err.$hos

#ssh yanos@b103ws$hos 'hostname;pkill -u yanos'
#ssh yanos@b103ws$hos 'hostname;ps'



####
@ i = $i + 4

end
